### ISSUE TITLE
[Bug Report] 네아로, 앱다운로드 유도 배너(링크) 클릭시 앱종료.(Android13, oauth:5.8.0)

### ISSUE THREAD

**Issue by JeongYeongKim** [naver/naveridlogin-sdk-android#102]
https://developers.naver.com/forum/posts/35149

# Bug Report

* 문의 내용

환경 : 안드로이드앱

build.gradle : implementation 'com.navercorp.nid:oauth:5.8.0'

test device : Pixel 2 XL (play store 없음)

Api : Api 33 (Android 13.0,Tiramisu)

증상 : 구글플레이콘솔에서 앱업데이트 사전출시보고서에 ActivityNotFoundException로 인해 앱 종료됨

원인 : 앱다운로드 유도배너 클릭시 play store가 없어서 발생하는것으로 짐작됨.

**Comment by DayeonLee-0** [comment]
@JeongYeongKim 님 안녕하세요.

네아로 SDK 담당자입니다.

포럼에 동일한 문의를 남겨주셔서 해당 문의에 코멘트 남겨두었습니다.

개발에 참고 부탁드립니다.
