### ISSUE TITLE
INSTALL_PARSE_FAILED_MANIFEST_MALFORMED 발생 건

### ISSUE THREAD

**Issue by jiinyou** [naver/naveridlogin-sdk-android#11]
Android 12 Beta 환경에서 아래와 같이 빌드 에러가 발생하여 검증에 어려움이 있습니다.

com.nhn.android.naverlogin.ui.OAuthCustomTabActivity: Targeting S+ (version 10000 and above) requires that an explicit value for **android:exported** be defined when intent filters are present

OAuthCustomTabActivity 액티비티에 android:exported 추가 요청드립니다.
rf. https://medium.com/androiddevelopers/lets-be-explicit-about-our-intent-filters-c5dbe2dbdce0

감사합니다.

**Comment by mydamyda** [comment]
안녕하세요.

네아로SDK 담당자입니다.

해당 이슈는 위에 있는 코멘트대로 override 처리로 회피가 가능하며,

최신 버전인 v5.0.0부터 대응하였습니다.

감사합니다.
