### ISSUE TITLE
Android 12 and higher are required to specify an explicit value for 'android:exported' Build Error occured

### ISSUE THREAD

**Issue by utinfra** [naver/naveridlogin-sdk-android#14]
![image](https://user-images.githubusercontent.com/44595839/134648194-21d34fc8-a305-4f96-af6d-9d759432e795.png)
ㅠㅠ

**Comment by utinfra** [comment]
android:exported 값 좀 넣어주세요. ㅠ

**Comment by leesgit** [comment]
저는 일단 메니페스트에 
<activity
            android:name="com.nhn.android.naverlogin.ui.OAuthLoginActivity"
            android:exported="true"
            android:theme="@style/Theme.AppCompat.Light.Dialog" />

        <activity
            android:name="com.nhn.android.naverlogin.ui.OAuthLoginInAppBrowserActivity"
            android:configChanges="orientation|screenSize"
            android:exported="true"
            android:label="OAuth2.0 In-app" />

        <activity
            android:name="com.nhn.android.naverlogin.ui.OAuthCustomTabActivity"
            android:configChanges="orientation|screenSize"
            android:exported="true"
            android:launchMode="singleTask"
            android:theme="@android:style/Theme.Translucent.NoTitleBar">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                <data
                    android:host="authorize"
                    android:path="/"
                    android:scheme="naver3rdpartylogin" />
            </intent-filter>
        </activity>

 android:exported="true" 넣어 주었습니다.

**Comment by kimymym** [comment]
AndroidManifest.xml 에 아래 한줄만 넣으셔도 merge 되면서 동작됩니다.

<activity android:name="com.nhn.android.naverlogin.ui.OAuthCustomTabActivity"
  android:exported=true />

(intent-filter 를 사용하는 경우에만 exported 체크가 진행됩니다)

**Comment by mydamyda** [comment]
안녕하세요.

네아로SDK 담당자입니다.

해당 이슈는 위에 있는 코멘트대로 override 처리로 회피가 가능하며,

최신 버전인 v5.0.0부터 대응하였습니다. 

감사합니다.
