### ISSUE TITLE
NaverIdLoginSDK.initialize 초기화 오류

### ISSUE THREAD

**Issue by leesgit** [naver/naveridlogin-sdk-android#20]
NaverIdLoginSDK.initialize(context, {OAUTH_CLIENT_ID}, {OAUTH_CLIENT_SECRET}, {OAUTH_CLIENT_NAME})
초기화 호출 시 NidLog 관련 lateinit property instance has not been initialized 발생합니다.

    fun init() {
        instance = if (BuildConfig.BUILD_TYPE.equals("debug", ignoreCase = true)) {
            DebugNidLog()
        } else {
            ReleaseNidLog()
        }
    }

NidLog에서 init 부분이 호출 안되는 것 같습니다.

**Comment by leesgit** [comment]
임시 방편으로 
NidLog.init()
NaverIdLoginSDK.initialize(context, {OAUTH_CLIENT_ID}, {OAUTH_CLIENT_SECRET}, {OAUTH_CLIENT_NAME})

사용 중 입니다.

**Comment by mydamyda** [comment]
안녕하세요.

네아로SDK 담당자입니다.

초기화시 `NaverIdLoginSDK.showDevelopersLog(true)` 와 같은 방식으로 오류를 회피할 수 있습니다.

리폿해주신 부분에 대해서는 빠르게 패치하여 배포하도록 하겠습니다.

감사합니다.

**Comment by dec207** [comment]
5.1.1에서 다시 발생하고 있습니다.
