### ISSUE TITLE
5.0.0 guide 문서 내용(4. 초기화) 업데이트 요청

### ISSUE THREAD

**Issue by dalcomdev** [naver/naveridlogin-sdk-android#23]
아래 초기화 관련 내용중에 메서드 호출부분이 정정되어야 합니다. 계층구조를 표현하기 위하여 dot 으로 구분하여 표시할 수도 있지만,  NaverIdLoginSDK.initialize() 과 같이 실제 static 메서드 호출예제와 혼합하여 사용되어져, 가이드 문서에서 혼동을 주고 있습니다.
  - NidOAuthLogin.logout() --> NidOAuthLogin().logout()
  - NidOAuthLogin.callDeleteTokenApi() --> NidOAuthLogin().callDeleteTokenApi()

> https://developers.naver.com/docs/login/android/android.md#4--%EC%B4%88%EA%B8%B0%ED%99%94

[](https://developers.naver.com/docs/login/android/android.md#4--%EC%B4%88%EA%B8%B0%ED%99%94)4. 초기화 
네아로SDK를 애플리케이션에 적용하려면 다음과 같은 코드를 추가해 네이버 로그인 인스턴스를 초기화합니다.
NaverIdLoginSDK.initialize(context, {OAUTH_CLIENT_ID}, {OAUTH_CLIENT_SECRET}, {OAUTH_CLIENT_NAME})

...
중략
...

참고
NaverIdLoginSDK.initialize() 메서드가 여러 번 실행돼도 기존에 저장된 접근 토큰(access token)과 갱신 토큰(refresh token)은 삭제되지 않습니다.
기존에 저장된 접근 토큰과 갱신 토큰을 삭제하려면 _**NidOAuthLogin.logout()**_ 메서드나 _**NidOAuthLogin.callDeleteTokenApi()**_ 메서드를 호출합니다.

**Comment by mydamyda** [comment]
안녕하세요.

네아로SDK 담당자입니다.

wiki 내 [최신 가이드 문서](https://github.com/naver/naveridlogin-sdk-android/wiki/v5.0.1-%EC%9D%B4%EC%83%81-%EA%B0%80%EC%9D%B4%EB%93%9C)에 반영하였습니다.

개발자 센터도 곧 동기화하겠습니다.

좋은 의견 고맙습니다.
