### ISSUE TITLE
네아로 WebView 방식 호출시 타이틀: OAuth2.0 by WebView

### ISSUE THREAD

**Issue by dalcomdev** [naver/naveridlogin-sdk-android#28]
![Screenshot_20220218_162638](https://user-images.githubusercontent.com/9858389/154637536-47527626-64ad-49ce-bd7d-b114ee611dc9.png)

단말: 갤럭시 S21
OS: Android 12
release 빌드에서 네아로 WebView 방식 호출시 타이틀이 이렇게 나오고 있습니다.: OAuth2.0 by WebView
"네이버 아이디 로그인" 이런 표현이 나올거로 예상했는데, 정상적인 화면인지 문의 드립니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.
네아로SDK 담당자입니다.
해당 이슈는 v5.1.0 버전부터 해소되었습니다.
감사합니다.
