### ISSUE TITLE
기존 네아로 SDK 4.2.6 사용했다가 5.0.1로 업데이트 시 로그인 유지가 가능한가요?

### ISSUE THREAD

**Issue by yongjikyang** [naver/naveridlogin-sdk-android#30]
안녕하세요
기존 네아로 4.2.6 사용하다가 안드로이드 12 타켓을 변경 하면서 5.0.1로 업데이트하여 작업했는데
기존에 앱을 사용하고 있다가 앱을 업데이트시 로그인이 유지 안되고 있는데 유지 안되는게 맞는건가요?
기존 로직은 
OAuthLogin.getInstance().refreshAccessToken을 호출하여 acesstoken 여부로 로그인 유지 여부를 체크하였습니다.
5.0.1로 변경하면서는 방식이 변경되어  NidOAuthLogin().callRefreshAccessTokenApi 로 체크했는데 적용이 안되서 
 if (NidOAuthLoginState.OK == NaverIdLoginSDK.getState()) 
으로 체크해도 체크를 할 수 없습니다.

해당 방법을 우회할려면 어떤식으로 개발을 해야 하는지 알려주시면 감사하겠습니다.

**Comment by yongjikyang** [comment]
디버깅 해보니깐 encryptedPreferences 로 바꼈는데 이전 키에 대한 마이그레이션 코드가 없는것 같네요 😭

**Comment by DayeonLee-0** [comment]
안녕하세요.
네아로SDK 담당자입니다.
v5.1.0 버전부터 마이그레이션 로직이 추가되었습니다.
감사합니다.
