### ISSUE TITLE
oauth-5.0.1.aar 파일 어디에 있나요?

### ISSUE THREAD

**Issue by Suanna01** [naver/naveridlogin-sdk-android#31]
네이버 Developers에서 Android용 네아로SDK를 Github에서도 다운받을 수 있다고 했는데
해당 파일이 어디에 있는지 모르겠어서 글 남깁니다!
code를 zip파일로 다운받아 aar파일을 검색해봤는데 보이지 않습니다.
감사합니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.
네아로SDK 담당자입니다.
oauth-5.0.1.aar 파일은 아래 링크에서 다운로드하실 수 있습니다.

https://search.maven.org/artifact/com.navercorp.nid/oauth/5.0.1/aar

해당 링크는 wiki 내 [v5.0.1 이상 가이드](https://github.com/naver/naveridlogin-sdk-android/wiki/v5.0.1-%EC%9D%B4%EC%83%81-%EA%B0%80%EC%9D%B4%EB%93%9C)에서도 확인하실 수 있습니다.
감사합니다.
