### ISSUE TITLE
com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException 발생

### ISSUE THREAD

**Issue by hongwonyun** [naver/naveridlogin-sdk-android#38]
Caused by com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException
Protocol message contained an invalid tag (zero).

com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom (GeneratedMessageLite.java:1566)

androidx.security.crypto.EncryptedSharedPreferences.create (EncryptedSharedPreferences.java:120)
com.navercorp.nid.oauth.EncryptedPreferences.init (EncryptedPreferences.kt:22)
com.navercorp.nid.oauth.EncryptedPreferences.access$init (EncryptedPreferences.kt:13)
com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke (EncryptedPreferences.kt:18)
com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke (EncryptedPreferences.kt:17)
kotlin.SynchronizedLazyImpl.getValue (LazyJVM.kt:74)
com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences (EncryptedPreferences.kt:17)
com.navercorp.nid.oauth.EncryptedPreferences.set (EncryptedPreferences.kt:69)
com.navercorp.nid.oauth.NidOAuthPreferencesManager.setClientId (NidOAuthPreferencesManager.kt:52)
com.navercorp.nid.NaverIdLoginSDK.initialize (NaverIdLoginSDK.kt:55)

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.4.0부터 Google tink 초기화 이슈에 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
