### ISSUE TITLE
5.1.0 EncryptedPreferences.moveToData  SecurityException 발생

### ISSUE THREAD

**Issue by yellowdo** [naver/naveridlogin-sdk-android#44]
5.1.0 에 추가된 migration()함수에서 SecurityException를 발생 시키고 있습니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.
네아로SDK 담당자입니다.

v5.1.0에 추가된 `migration()`함수에서는 `SecurityException` 발생 여부에 따라
`SharedPreferences` -> `EncryptedSharedPreferences`
`EncryptedSharedPreferences` -> `EncryptedSharedPreferences`
를 구분하고 있습니다.

v5.0.0, v5.0.1에서 v5.1.0 이상으로 업그레이드를 한 경우 `SecurityException` 이 발생합니다.

감사합니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.
네아로SDK 담당자입니다.

v5.1.0에 추가된 migration()함수에서 `SecurityException`이 발생하는 것을 확인해 v5.1.1 에서 패치 예정입니다.

감사합니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.
네아로SDK 담당자입니다.
해당 이슈는 v5.1.1 버전부터 해소되었습니다.
감사합니다.
