### ISSUE TITLE
플레이스토 앱 제출시 에러

### ISSUE THREAD

**Issue by mk0116** [naver/naveridlogin-sdk-android#45]
Version of naveridlogin-android-sdk libraries
4.2.5

Expected behavior
에러 없이 플레이 스토어 리뷰 통과

Actual behavior
플레이스토어 업로드시 에러를 출력합니다.

Tested environment (Emulator? Real Device?)
Real Device

교차 앱 스크립팅
교차 앱 스크립팅에 취약한 WebView가 앱에 포함되어 있습니다. 자세한 내용은 [Google 고객센터 도움말](https://support.google.com/faqs/answer/9084685)을 확인하세요.

com.nhn.android.naverlogin.ui.OAuthLoginInAppBrowserActivity.runOnlyOnce
sv:deadline:07/03/2022

**Comment by DayeonLee-0** [comment]
안녕하세요 @mk0116 님
네아로SDK 담당자입니다.

해당 이슈는 v5.0.0 부터 해소되었습니다.
최신 버전인 v5.1.1 참고 부탁드립니다.

감사합니다.
