### ISSUE TITLE
네아로 5.x TASK 이슈

### ISSUE THREAD

**Issue by onetest0** [naver/naveridlogin-sdk-android#49]
안녕하세요.
현재 네아로 task관련 이슈가 발생하여 확인 및 수정 요청 드립니다.

이슈는 다음 두가지 입니다.

1. 다른앱(앱1) -> 네아로sdk연동앱(앱2) -> 네아로 호출 할 경우 앱1과 앱2의 task가 나눠짐 
 - task가 나눠짐에 따라 네아로 화면에서 홈키등으로 화면을 벗어났다 다시 돌아올때 여러가지 사이드 이펙트가 발생함
 - 앱2에서 직접 네아로를 호출할 경우에는 task가 분리되지 않음

2. 해당 상황을 방지하고자 앱2에서 네아로의 엑티비티에 excludeFromRecents="true"로 하여 홈키등으로 화면을 벗어났을때 네아로 엑티비티를 종료하게 할 경우
네아로 웹 -> 정상적으로 엑티비티 종료 및 에러 콜백
네아로 앱 -> recents에서는 사라지지만 엑티비티가 종료가 되지 않음 -> 다른 앱을 실행하는 엑션을 일으킬때 네아로 엑티비티 종료 및 에러 콜백

1번 이슈의 경우 별도의 task관리를 하지 않아도 task가 분리되며 여러 문제가 발생하게 됩니다. 네아로의 task가 분리되지 않게하거나 옵션을 줄 수 있게 수정 요청드립니다.

2번 이슈의 경우 네아로 웹 일 경우에는 홈키를 누르면 바로 ACTIVITY_IS_SINGLE_TASK 에러 콜백이 발생하지만
네아로 앱 일 경우에는 홈키를 눌러도 아무 동작을 하지 않습니다. (다른 앱을 실행하면 그때 ACTIVITY_IS_SINGLE_TASK 콜백 발생)
네이버 앱을 사용할 경우만 발생하는 현상으로 웹 인증처럼 바로 ACTIVITY_IS_SINGLE_TASK 콜백이 발생하도록 수정 요청드립니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.4.0부터 네이버앱 Intent에 flag를 설정할 수 있는 인터페이스가 추가되었습니다. (`NaverIdLoginSDK.naverappIntentFlag`)

개발에 참고 부탁드립니다.

감사합니다.
