### ISSUE TITLE
메뉴얼 업데이트가 필요해보입니다.

### ISSUE THREAD

**Issue by tangible-idea** [naver/naveridlogin-sdk-android#5]
https://developers.naver.com/docs/login/android/

1. AndroidX 사용시에 namespace도 androidx 관련 내용으로 업데이트가 필요해 보입니다.
2. gradle에 compile은 이미 deprecated 되어 대체가 필요해보입니다.

**Comment by mydamyda** [comment]
@tangible-idea 님 안녕하세요.

네아로 SDK v5.0.0을 업데이트하면서 문서를 최신화하였습니다.

자세한 내용은 [Wiki](https://github.com/naver/naveridlogin-sdk-android/wiki/v5.0.0-%EC%9D%B4%EC%83%81-%EA%B0%80%EC%9D%B4%EB%93%9C)를 참고해주세요.
