### ISSUE TITLE
유저 프로필 API 요청시 age, gender 등이 null로 내려오는 이슈

### ISSUE THREAD

**Issue by Sienna94** [naver/naveridlogin-sdk-android#52]
2022.09.14 에 해당 API로 요청했을 때는 age, gender 등의 value를 받아볼 수 있었습니다.
2022.09.16 에 동일하게 요청했을 때 age, gender, profileImage 등이 null로 내려옵니다. 
id 같은 경우에도 형식이 변경된 것 같은데요. (기존 : 숫자 -> 변경: 영대소문자 + 숫자). 
API response 부분에 수정이 있나요?

SDK 버전 4.2.6 과 5.1.1 에서 동일하게 발생합니다.

2022.09.14 응답 예시 (IDE 캡쳐, v4.2.6, v 5.1.1)
![image](https://user-images.githubusercontent.com/69448123/190553125-cf51526b-1cca-4489-9306-5600a0f52bed.png)
![image](https://user-images.githubusercontent.com/69448123/190553135-e2bbf88b-812c-4c73-a284-9024a9c9df26.png)

2022.09.16 응답 예시 (v4.2.6, v 5.1.1)
- `<?xml version=“1.0” encoding=“UTF-8" ?><data><result><resultcode>00</resultcode><message>success</message></result><response><id><![CDATA[rfCIIF1dXWbdS8TiA1Dg*********************]]></id><email><![CDATA[jsj947@naver.com]]></email><name><![CDATA[장서정]]></name></response></data>`
- NidProfileResponse
   resultCode=00
   message=success
   profile=NidProfile
     - id=rfCIIF1dXWbdS8TiA1Dg*******************
     - nickname=null
     - name=장서정
     - email=jsj947@[naver.com](http://naver.com/)
     - gender=null 
     - age=null
     - birthday=null
     - profileImage=null
     - birthYear=null
     - mobile=null

**Comment by DayeonLee-0** [comment]
안녕하세요. 

Android 네아로 SDK 담당자입니다.

2021년 5월 1일 이후 등록된 애플리케이션에 대해서 Unique ID(이용자 식별자)의 발급 스펙이 변경되었습니다.

[개발자센터 공지사항](https://developers.naver.com/notice/article/7524) 참고 부탁드립니다.

감사합니다.
