### ISSUE TITLE
5.2.0 에 authenticate 예제가 잘못되어 있습니다.

### ISSUE THREAD

**Issue by mym0404** [naver/naveridlogin-sdk-android#54]
`NaverIdLoginSDK.authenticate` 는 이제 두 번째 인자로 `ActivityResultLauncher`를 받는데, [예제](https://github.com/naver/naveridlogin-sdk-android/wiki/v5.2.0-%EC%9D%B4%EC%83%81-%EA%B0%80%EC%9D%B4%EB%93%9C#52-authenticate-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8)에선 그렇지 않습니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로SDK 담당자입니다.

wiki 내 [v5.2.0 이상 가이드](https://github.com/naver/naveridlogin-sdk-android/wiki/v5.2.0-%EC%9D%B4%EC%83%81-%EA%B0%80%EC%9D%B4%EB%93%9C#52-authenticate-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8)에 반영하였습니다.

감사합니다.
