### ISSUE TITLE
5.2.0에 `authenticate` API가 이상적이지 않습니다.

### ISSUE THREAD

**Issue by mym0404** [naver/naveridlogin-sdk-android#55]
갑자기 `5.2.0`에 이걸 인자로 받는 이유를 잘 모르겠는데, API 자체가 일관성있게 작동하지 않습니다.

- `authenticate` 함수에 `AcitivtyResultaLauncher`를 인자로 받음으로써 Native가 아닌 다른 플랫폼에서 해당 SDK를 이용하려 할 때, Activity의 Lifecycle과의 어색한 연동때문에 사용하기가 까다로워집니다. (`Activity`를 직접적으로 사용하지 않는 플랫폼에서 `registerForActivityResult` 를 초기화하는 시점을 결정할 수 없고(하지만 이는 독스에 따르면 RESUMED 전에 unconditional하게 등록되어야 합니다), Android로의 의존성이 큽니다.)
- 코드를 자세히 본건 아니지만 Refreshtoken의 유무에 따라 어쩔땐 `ActivityResultLauncher`의 콜백으로 결과가 반환되고 어쩔땐 `authenticate` 함수의 세 번째 인자인 callback으로 결과가 반환됩니다.

제가 잘 이해한 것인진 모르겠지만 개선이 필요해보입니다. 
현재 `5.2.0` 에서 fix된 여러 이슈들이 프로젝트에 문제를 일으키고 있는 상황이라 [rn package](https://github.com/react-native-seoul/react-native-naver-login) 를 손보고 있는데, `5.2.0` 로 내부적인 코드를 변경하는데 애로사항이 있습니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로SDK 담당자입니다.

v5.2.1에서 `authenticate()`메서드 개선하였습니다.

감사합니다.
