### ISSUE TITLE
5.2.0 네이버 로그인 일때 user_cancel 오류 발생합니다.

### ISSUE THREAD

**Issue by bshbman** [naver/naveridlogin-sdk-android#60]
5.2.0버전 적용했고, debug 시에는 문제 없지만 릴리즈 버전에서는 네이버 로그인 일때 user_cancel 오류 발생합니다.
확인 부탁드립니다.

**Comment by DayeonLee-0** [comment]
안녕하세요. 

네아로 SDK 담당자입니다.

해당 이슈는 네아로 SDK v5.4.0에서 해소되었습니다.

개발에 참고 부탁드립니다.

감사합니다.

**Comment by chrislee92** [comment]
혹시 웹도 똑같은 증상이 있는데 user_cancel가 뜹니다 해결 방안이 있을까요?
