### ISSUE TITLE
5.2.0 버전 wiki의 authenticate() 예제 코드에서 설명이 더 필요 한 것 같습니다.

### ISSUE THREAD

**Issue by sinoso** [naver/naveridlogin-sdk-android#62]
[https://github.com/naver/naveridlogin-sdk-android/wiki/v5.2.0-%EC%9D%B4%EC%83%81-%EA%B0%80%EC%9D%B4%EB%93%9C#52-authenticate-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8](url)

위의 
5.2. authenticate() 메서드를 이용한 로그인 에서

적혀져있는 설명에 의하면, 갱신 토큰의 유무에 의해서 
callback으로 호출이 될 수도, launcher의 ActivityResultCallback이 호출 될 수도 있음을 이야기 하는 것으로 보입니다.

하지만 예제에서
authenticate 메소드를 통해서 전달되는 
launcher와 callback은 왜 거의 동일한 코드를 가져야 하는지,

갱신 토큰의 유무와 특정 결과에 따라 어느 상황에 어떤 콜백이 실행 되는지
예제를 보고는 알 수가 없습니다.

launcher와 callback은 왜 거의 동일한 코드를 가져야 하는지,
어느 상황에서 각각의 콜백이 호출되는지 
관련된 설명을 예제코드에도 추가 해 주셨으면 합니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로SDK 담당자입니다.

[wiki 가이드 문서](https://github.com/naver/naveridlogin-sdk-android/wiki/v5.2.1-%EA%B0%80%EC%9D%B4%EB%93%9C)에 설명을 추가하였습니다.

감사합니다.
