### ISSUE TITLE
5.x.x 에서 사용자 프로필 정보 enc_id 누락 문의

### ISSUE THREAD

**Issue by jjangna** [naver/naveridlogin-sdk-android#69]
5.2.0 버전을 적용 중 사용자 프로필 정보(NidProfile)에서 enc_id가 제거된 것을 확인했습니다. 
모바일웹, 피씨웹, 아이폰앱, 안드로이드앱에서 enc_id를 사용하고 있어 당사의 앱에서 이슈가 되고 있습니다.
enc_id를 다시 넣어 주실 수 있는지 문의 드립니다.
그리고 향후 enc_id가 타 플랫폼(웹, IOS)에서도 제거 될 가능성이 있는지 문의 드립니다.
감사합니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

Android 네아로 SDK 담당자입니다.

Android 네아로 SDK 인터페이스가 아닌 회원 프로필 조희 API(https://openapi.naver.com/v1/nid/me)를 직접 호출 부탁드립니다.

감사합니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.5.0에서 프로필 API 응답 항목으로 `encId` 가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
