### ISSUE TITLE
네트워크 단절 환경에서 startOauthLoginActivity 콜백이 오지 않습니다.

### ISSUE THREAD

**Issue by ajw227** [naver/naveridlogin-sdk-android#7]
제목 그대로 입니다.

재현 방법

1. 디바이스를  비행기 모드로 변경 합니다.
2. startOauthLoginActivity 호출
3. 네트워크 오류 팝업 노출 확인
4. 취소

startOauthLoginActivity 함수 내 checkConnectivity 콜백의 retry 가 false 에 대한 처리를 해야 할 것 같습니다. 

버그가 빨리 고쳐 졌으면 좋겠네요!
감사합니다. 좋은 하루 되세요!

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로SDK 담당자입니다.

해당 이슈는 v5.1.0 버전부터 해소되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
