### ISSUE TITLE
customTab에서의 callback 중복 호출 이슈

### ISSUE THREAD

**Issue by nhnjskim** [naver/naveridlogin-sdk-android#72]
NidOAuthBridgeActivity가 의도치 않게 destroy 될 시 LocalBroadcastManager에 listener가 register 된채로 남아 있어 정상적인 로그인을 진행할 시 callback이 중복적으로 호출됩니다.

* 네아로 SDK 버전
    * 5.3.0(JDK 11)

### 재현 과정
* 해당 repository 샘플앱을 수정하여 확인
* AndroidManifest.xml 
    * android:launchMode="singleTask" 추가
``` xml
<activity
    android:name=".MainActivity"
    android:label="네아로SDK Sample"
    android:exported="true"
    android:launchMode="singleTask">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />

        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
</activity>
```
* MainActivity.kt
    * 로그인 callback onCLickListener에서 OAuthLoginCallback 의 onSuccess() 메서드에 log 추가
``` kotlin
override fun onSuccess() {
    Log.e("bug", "login success")
    updateView()
}
```
1. 로그인(CALLBACK) 버튼을 클릭하여 NidOAuthBridgeActivity create.
2. 앱을 백그라운드 상태로 변경 후 앱 아이콘 클릭 -> single task로 인하여 해당 NidOAuthBridgeActivity가 destroy 됨(lastErrorCode는 NidOAuthErrorCode.ACTIVITY_IS_SINGLE_TASK).
3. 로그인(CALLBACK) 버튼을 다시 클릭하여 새로운 NidOAuthBridgeActivity create.
4. 해당 NidOAuthBridgeActivity에서 로그인 진행.
5. callback.onSuccess()가 중복적으로 호출 되어 log가 중복적으로 Logcat에 찍힘.

<img width="675" alt="스크린샷 2023-01-06 오전 1 38 34" src="https://user-images.githubusercontent.com/95207923/210833053-d5b2ea8d-1ec7-4878-a4de-4d10c96c0f61.png">

해당 문제에 대해 개인적으로 확인 결과 NidOAuthIntent.getCustomTabsIntent에서 로직상 registerReceiver만이 중복적으로 호출되어 문제가 발생하는 것으로 사료됩니다.(unregisterReceiver가 onReceive 되어야만 호출됩니다.) 그러함에 따라 위 재현 과정에서 2, 3번을 반복하여 진행하면 반복하여 진행한 횟수만큼 추가적으로 callback이 호출됩니다.

``` kotlin
val instance = LocalBroadcastManager.getInstance(context)
instance.registerReceiver(object : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent?) {
        listener(intent)
        instance.unregisterReceiver(this)
    }
}, IntentFilter(NidOAuthCustomTabActivity.ACTION_NAVER_CUSTOM_TAB))
```
해당 이슈에 대해 확인해주시면 감사하겠습니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

해당 이슈는 네아로 SDK v5.4.0에서 해소되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
