### ISSUE TITLE
EncryptedPreferences.kt line 46

### ISSUE THREAD

**Issue by whath** [naver/naveridlogin-sdk-android#74]
![image](https://user-images.githubusercontent.com/23625073/211955145-79b5fde5-9a56-475f-8c15-5615a7737725.png)

We had this problem in previous versions, probably 5.1
Or 5.2, for which we upgraded to 5.3, this problem is currently re-occurring, please help

version : 5.3.0
device : GCE x86 phone (android 9) \  pixel 6 (android 12)

**Comment by whath** [comment]
hey , any reply for this????????????????

**Comment by DayeonLee-0** [comment]
Hello, @whath.

I'm an Android Developer for Naver Id Login SDK.

This issue has been patched in SDK v5.4.0.

Please refer to the development.

Thank you.
