### ISSUE TITLE
[Bug Report] com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException

### ISSUE THREAD

**Issue by Hooooong** [naver/naveridlogin-sdk-android#81]
# Bug Report
### 사용중인 네아로 SDK 버전

v5.4.0

### Android 버전

OS : 12, 13

### 재현되는 기기 모델명

- Galaxy Z Fold4, Galaxy S23 Ultra, Galaxy S23+, Galaxy Z Flip4, Galaxy Note20 5G, Galaxy S22+, Galaxy S20 FE 5G

### 이슈 명세

com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException 이슈가 발생하고 있습니다. 5.4 이전 버전에도 crypto 관련 오류가 발생했는데, 또 발생하는것 같습니다.

### Stack trace
```
Fatal Exception: java.lang.RuntimeException
com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either that the input has been truncated or that an embedded message misreported its own length.

```

**Comment by joshseo13** [comment]
Galaxy Note9 도 추가로 발생하고 있습니다

**Comment by joshseo13** [comment]
manifest 파일에 application android:allowBackup="false" 로 우회하여 문제 해결했습니다

**Comment by pparkppark** [comment]
> 
저는 동일한 처리를 했는데도 오류가 납니다. 혹시 앱에서 별도로 EncryptedSharedPreference를 사용하고 계신가요?

**Comment by joshseo13** [comment]
저도 임시로 했던 방법에서 다시 증상 재현되어서 문제점 찾아 스텍트레이스 여기에 다시 보고할 예정입니다.

**Comment by pparkppark** [comment]
저는 EncryptedSharedPreference + 네아로 4.x 사용하고 있다가, 네아로만 5.x로 변경했더니 해당 문제가 발생하세요...
네아로를 사용하지 않는 앱은 EncryptedSharedPreference를 사용함에도 오류가 발생하지 않습니다...

**Comment by pparkppark** [comment]
> 저는 EncryptedSharedPreference + 네아로 4.x 사용하고 있다가, 네아로만 5.x로 변경했더니 해당 문제가 발생하네요... 네아로에서 오류+제 앱에서 오류... 네아로를 사용하지 않는 앱은 EncryptedSharedPreference를 사용함에도 오류가 발생하지 않습니다.

추가로 변경된것을 찾아보니... java8에서 11로 변경되었습니다. 영향이 있을지 모르겠습니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.8.0에서 InvalidProtocolBufferException 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
