### ISSUE TITLE
[문의 사항] 로그인 실패 시 errorCode 분기 가능 여부 문의

### ISSUE THREAD

**Issue by yellowdo** [naver/naveridlogin-sdk-android#82]
# 문의 사항
### 문의 사항
네이버 로그인 실패 중 에러코드 분기가 필요합니다. 
`인증을 진행할 수 있는 앱이 없습니다.` 에 대한 에러코드는 별도로 분기 가능한지 문의 드립니다.

**Comment by Kim-DongGeun** [comment]
![스크린샷 2023-05-10 오전 11 29 02](https://github.com/naver/naveridlogin-sdk-android/assets/12513110/1786a550-d964-472c-a424-99c042bf429b)
다른 에러들도 에러코드로 분기해서 처리할 수 있도록 변경되면 좋을 것 같습니다 
확인 한번 부탁드립니다!

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

v5.6.0 에서 인증을 진행할 수 있는 앱(네이버앱이나 커스텀탭)이 없는 경우 발생하는 'NO_APP_FOR_AUTHENTICATION' 에러코드가 추가되었습니다.

코멘트로 남겨주신 내용 또한 검토해 보겠습니다.

감사합니다.
