### ISSUE TITLE
[Bug Report] AGP >= 8.0, Gradle 8.0 이상 업그레이드 진행 시, 발생하는 no_catagorized_error 이슈

### ISSUE THREAD

**Issue by NamJa** [naver/naveridlogin-sdk-android#88]
# Bug Report
## 재현 환경
AGP 8.0.1, Gradle 8.0, R8(Proguard) 적용된 상태입니다.
### 사용중인 네아로 SDK 버전
5.4.0, 5.5.0
android security: androidx.security:security-crypto:1.1.0-alpha06
### Android 버전
Android 13
### 재현되는 기기 모델명
갤럭시 S20+, Fold4, zFlip4
## 이슈
-keep public class com.navercorp.nid.** {
public *;
}
proguard rules를 상기 코드와 같이 설정하였음에도 로그인이 진행되지 않고,
errorCode: no_catagorized_error, errorCodeDescription: no_catagorized_error
로 에러가 출력됩니다.

### 이슈 해결 방법
임시 방편일 수 있겠지만 해결책을 제시하자면,

gradle 8.0으로 올라가게 되면서, gradle 설정값 중
android.enableR8.fullMode가 기본적으로 true로 설정되면서 발생하는 문제였습니다.
gradle.property에서
android.enableR8.fullMode = false로 설정하면 라이브러리 내부에 걸려있는 난독화 설정이 해제되어 로그인 절차를 밟을 수 있습니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

Android 네아로 SDK 담당자입니다.

해당 이슈는 난독화 이슈로 아래 프로가드를 적용 부탁드립니다.

https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro

현재 샘플앱에도 해당 프로가드가 적용되어 있습니다.

https://github.com/naver/naveridlogin-sdk-android/blob/main/Samples/proguard-rules.pro

개발에 참고 부탁드립니다.

감사합니다.

**Comment by NamJa** [comment]
retrofit proguard도 동일하게 적용된 상태입니다

**Comment by Shik1266** [comment]
@DayeonLee-0 안녕하세요, 혹시 flutter SDK 에서도 동일한 에러 발생하는데 해결방안이 있을까요?
