### ISSUE TITLE
[문의 사항] 네이버 아이디로 로그인 프로필 조회 '실명 인증 여부 값' 문의

### ISSUE THREAD

**Issue by jisoo-baek** [naver/naveridlogin-sdk-android#95]
# 문의 사항
### 문의 사항
네이버 아이디로 로그인시 프로필 조회 NidOAuthLogin().callProfileApi()에서
사용자 실명 인증 여부값 'realnm' 은 5.7.0 버전에 존재하지 않습니다. 
Android 에서 Open API(https://openapi.naver.com/v1/nid/me) 통해 조회하면 될까요?  

### Reference
네이버 프로필 API 호출 문서 
https://developers.naver.com/docs/login/android/android.md#9--%ED%94%84%EB%A1%9C%ED%95%84-api-%ED%98%B8%EC%B6%9C

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.8.0에서 프로필 조회 API 명세 외 다른 값도 받을 수 있는 인터페이스(`NidOAuthLogin().getProfileMap(nidprofileCallback)`)가 추가되었습니다.

[가이드 문서](https://github.com/naver/naveridlogin-sdk-android/wiki/v5.8.0-%EC%9D%B4%EC%83%81-%EA%B0%80%EC%9D%B4%EB%93%9C-(%EC%B5%9C%EC%8B%A0-v5.8.0)#1134-getprofilemap) 참고 부탁드립니다.

감사합니다.
